### ISSUE TITLE
Peer/User Review

### ISSUE THREAD

**Issue by gkertaseferi** [OpenLiberty/draft-guide-microprofile-health#10]
What you’ll learn

- [ ] Before the service reports its state, it should check what it has to be available. Depending on what the service has or what is provided to it, it can report whether it is healthy or not via the Microprofile Health API implementation. A self check can be anything related to the service. It could be a dependency, a successful connection to an endpoint, a system property and many others. 
=>  How about: 
A service's state can depend on a number of factors, such as availability of resources (e.g. a database,
endpoint connections).  In order for a service to report its state, it should first check everything it considers required for healthy operation and then based on these checks, it reports the state through the MicroProfile Health API as either UP or DOWN.
[I think the first paragraph is better. Also, It was reviewed by an SME person, i might just add " database"] 

- [x] i.e. in maintenance - this should be an e.g. [changed to or]

Try what you’ll build

- [x] From here, you can see the health of the two services as well as the overall health outcome of the applicaiton. => application misspelled. 

Adding health check to inventory service

- [x]  The state of inventory service is UP if isHealthy returns true and vice versa. => I think vice versa here is not used right and that it would be better to say "The state of inventory service is UP if isHealthy returns true and DOWN if isHealthy returns false".

Building and running the application

- [x] This property is found in /finish/CustomConfigSource.json.  =>  the directory is wrong /resources/CustomConfigSource.json. 

Testing Health Check

- [ ] This method uses the helper method getActualState() to return the actual state of each service from this JsonArray =>  Didn't we say that we won't refer to helper methods/classes or I misunderstood? [_we dont show the class, but we talk about the methods used in the code snippets only]_

- [x]  The testIfInventoryServiceIsDown() method follows the similar procedure as in the previous test case. => The testIfInventoryServiceIsDown() method follows a similar procedure as in the previous test case.

- [x]  It first checks if the services states are UP => It first checks if the services' states are UP. 

- [x]  With the property update, we send a request to check the services states again. => With the property update, we send a request to check the services' states again.

- [x] Lastly, we validate the state of the inventory service by asserting if it is DOWN but the ProeprtiesResource service is UP. => I think that this should be rephrased too.  Maybe something like: 
   Lastly, we validate the state of the inventory service by asserting "it is" DOWN but(and??? I don't know exactly what you mean) the ProeprtiesResource service is UP. => ProeprtiesResource is misspelled.

**Comment by gkertaseferi** [comment]
Also, we decided to have  provided the dependency provided in the pom.xml and just describe it.

**Comment by Ahmad-Ayyoub** [comment]
Here: https://github.com/OpenLiberty/draft-guide-microprofile-health/commit/e9a302d63ea0f4434d6dd5ac600186de4ae91faa
