### ISSUE TITLE
Test failed with latest OL

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-microprofile-health#12]
Steps to reproduce the failure: 

1. Change finish/pom.xml to use the "LATEST" version of OL release:
`<artifactId>openliberty-runtime</artifactId>`
            `<version>17.0.0.3</version>`
=> 
`<artifactId>openliberty-runtime</artifactId>`
            `<version>LATEST</version>`

1. Run "mvn clean install" to launch the test cases for this application. 

1. You will see the test case failure. 

The failure looks like a success code of 200 instead of a service unavailable code of 503 is returned; thus the test case failed.

**Comment by evelinec** [comment]
@gkertaseferi can you pls push the fix into your fork/branch and then create a PR to master? Thanks.

**Comment by Ahmad-Ayyoub** [comment]
Fixed here: https://github.com/OpenLiberty/draft-guide-microprofile-health/pull/17
