### ISSUE TITLE
Need to resolve large repo size issue

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-microprofile-health#13]

**Comment by Ahmad-Ayyoub** [comment]
fixed here: https://github.com/Ahmad-Ayyoub/draft-guide-microprofile-health

**Comment by Ahmad-Ayyoub** [comment]
I can not PR to master, I was wondering if I can reduce the master size directly rather.

**Comment by Ahmad-Ayyoub** [comment]
Fixeed
