### ISSUE TITLE
Code Cleanup 

### ISSUE THREAD

**Issue by Ahmad-Ayyoub** [OpenLiberty/draft-guide-microprofile-health#16]
Clean up SystemResource class to match mp-health guide

**Comment by evelinec** [comment]
@Ahmad-Ayyoub Clean up to get rid off the extra mp-config content in the code.

**Comment by Ahmad-Ayyoub** [comment]
Fixed here: https://github.com/Ahmad-Ayyoub/draft-guide-microprofile-health/commit/bfa2347f728d36e89f0c5105e0bf199dfe9e7a05
