### ISSUE TITLE
Health code needs to handle service being down

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/draft-guide-microprofile-health#19]
If the other service can't be connected to (rather than just returning http error), then an exception will be thrown that needs to be handled.

The Health code needs to do something like this:

    try {
      String url = SystemClient.buildUrl("http", "localhost", config.getPortNumber(), "/system/properties");
      Client client = ClientBuilder.newClient();
      Response response = client.target(url).request(MediaType.APPLICATION_JSON).get();

      if (r.getStatus() != 200) {
        return false;
      }
      return true;
    } catch (Exception e) {
      return false;
    }

**Comment by Ahmad-Ayyoub** [comment]
Fixed here: https://github.com/OpenLiberty/draft-guide-microprofile-health/pull/20/commits/ac823b7835ca30d9b6d6fd1751ff309739ff3713
