### ISSUE TITLE
Need example of output

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-microprofile-health#21]
The guide needs to include an example of the output that you get and (briefly) explain what it shows. I tried adding health to my app and I didn't have the scoping annotation in quite the right place so it was showing me only the app's health and not the service's health. We spent ages trying to work out what it *should* show (as it didn't look right but we weren't sure what was missing).

**Comment by Ahmad-Ayyoub** [comment]
Fixed here: https://github.com/OpenLiberty/draft-guide-microprofile-health/pull/23
