### ISSUE TITLE
Review consistency of server.xml with other guides

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-microprofile-health#22]
The war file name and specification of the context root in the `server.xml` is different for the MP guides than for, say, the REST intro guide (which specifies the context root in the `pom.xml`, not the `server.xml`, and has a simple war file name).

Was there a specific reason for doing it differently or do these need to be updated to be consistent with other guides? (and do other guides need to be made more consistent too?)

**Comment by Ahmad-Ayyoub** [comment]
Fixed here: https://github.com/OpenLiberty/draft-guide-microprofile-health/pull/23
