### ISSUE TITLE
Bad links and terms

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microprofile-health#29]
- Rephrase to use "services" or "microservices" instead of "RESTful application" or "RESTful service" to be consistent with the other guides and the title/abstract.  "Application" is still alright to be used depending on context.

_You will learn how to use the MicroProfile Health feature to report the health of a RESTful application. A health check allows your RESTful service to participate in the decision-making process about its health._

_You will add health checks to report the states of the system and inventory RESTful services in an inventory manager application. This application and the services in it are provided for you. To learn how to create a RESTful application, see Creating a RESTful web service._

Should review the whole guide to fix what is appropriate besides the above.

- Broken or bad links:
  - _To learn how to configure the file, see Configuring Microservices using MicroProfile Config._:  This points to the interactive guide, which is incorrect?
  - _Learn more about the @Inject annotation from Handling dependencies with RESTful web services._:  The title for the CDI guide is not final yet and we have a bad link that points to the REST guide?

**Comment by Ahmad-Ayyoub** [comment]
Resolved here: https://github.com/OpenLiberty/draft-guide-microprofile-health/pull/28/commits/5e3380f76ad29a732ba39892390be3d0ec781f49

**Comment by Ahmad-Ayyoub** [comment]
@evelinec can you please close this ?

**Comment by evelinec** [comment]
@yeekangc can we close this one?

**Comment by yeekangc** [comment]
"You’ll explore how to check the health of a microservice with MicroProfile Health."  -- This is inconsistent with the abstract i.e. page-description and it doesn't a key factor.  Consider "You'll explore how to report and check the health ..."

The CDI title still needs to be updated but I see we have a separate issue for that.

"Microservices" in "Configuring Microservices using MicroProfile Config" should be in lower case?

Is the "1-" and "2-" done with proper Asciidoc syntax?  Or, there is issue and this is a workaround?

**Comment by yeekangc** [comment]
We can close after the above has been addressed.

**Comment by Ahmad-Ayyoub** [comment]
Here: https://github.com/OpenLiberty/draft-guide-microprofile-health/pull/34/commits/f7d2fb9260ba0f96ab09c89ad327c0509e204b1a

**Comment by yeekangc** [comment]
Closing for now.  Will reopen or file new issue if necessary.
