### ISSUE TITLE
Review Comments for 1/30's Draft

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microprofile-health#3]
- What you'll learn:
  - After the introductory sentence, we should explain what is MP Health;
  - Then, we can talk about the UP or DOWN details, what we have in the guide, and what the users will work with. [fixed, @evelinec]

- These can go or need to be rewritten -- MP Health doesn't exactly do these:
  - "The great benefit from adding a health check is that it helps in machine to machine [not yet] communications, monitoring and knowing which services are performing in the application."
  - "A health check is a method for assessing the states of the services in an application to know the overall performance." [fixed]

- Try what you'll build:
  - "You can also verify states of the two RESTful services by pointing to their endpoints:" -- I don't think we are verifying any state here?  We are actually invoking the services? [fixed]

- "Adding health check to inventory application" -- "Adding health check" or "Adding health check to RESTful services" can work? [fixed]

- And, I don't think we refer to the services as "PropertiesResource" or "InventoryResource" in the other guides? [fixed]

- "The healthy state of the PropertiesResource service is simulated by reading the system property of the host. If the system property wlp.server.name is defaultServer, then the state is UP, otherwise, it is DOWN." -- The idea is that the service will self-check and the report its health.  We should explain the why. [fixed]

- "This service reports its healthy state depending on two conditions:" for Inventory service -- Same as last comment in that we need to explain the why. [fixed]

- Need to fix the links to the guides referenced.  They shouldn't point to GitHub repos but to pages on OL website directly. [fixed, but we still need to update after all draft guides have their new html page on OL]

- The CustomConfigSource.json should be put under a resources folder like how we are doing it for the other guides. [fixed]

- We should consider something better than “Testing Services State” and the terminology doesn't map to what we have been using or what is typical of MP Health. [fixed]

- The same applies to the test method names.  Consider something like testHealthEnpoint, testInventoryServiceHealth etc. [left the same]

- Scope for MP Config in POM should be provided. [it is provided]

- /start and /finish aren't consistent or at least, isn't consistent with the guide?  'resource' should be 'resources'? [fixed]

- Are we sure we need both @BeforeClass and @Before for the tests? [fixed]

- Do not import .*; [fixed]

- Do we really need a setup() for HealthTest? [fixed]

- changeInventoryProperty() seems awkward to need to deal with Strings as input.  It can be improved? [fixed]

- Better name for returnMessage in JsonMessages? [this was already provided from mp-config]

- Remove ibm-web-ext.xml. [fixed]

- Update copyright statements to include ", 2018" where appropriate. [fixed]

- Should we explain why we have HealthCheck implemented in a separate class? [hmm not sure about that]
- Are we actually using 100 characters per line in code? [we are using 80? and all of the classes are intended based on that]

- And, double check code formatting too ... especially with use (or non-use) of newlines. [already fixed]

**Comment by Ahmad-Ayyoub** [comment]
Fixed here: https://github.com/OpenLiberty/draft-guide-microprofile-health/pull/4. 
Still not done with what you will learn section
