### ISSUE TITLE
Review on 3/13's draft

### ISSUE THREAD

**Issue by gkertaseferi** [OpenLiberty/draft-guide-microprofile-health#35]
Adding a health check to the inventory service

[] Otherwise, if the property is set to true, the service responds with a ERROR:
   ->
   Otherwise, if the property is set to true, the service responds with an ERROR:
**[This was reviewed by an ID, I think it is a not an, @sishida @evelinec (read full sentence), the ERROR is in a string referring to a message]**

[] While the server is running, navigate to the following URL to find the health endpoint that reports the 
   state of the two services:
   http://localhost:9080/health
   -> I think we don't need the bullet point and we can have something like 
   While the server is running, navigate to the `http://localhost:9080/health`  URL to find the health 
   endpoint that reports the state of the two services:

**[I think it should be obvious, since the whole guide is talking about this URL, @evelinec ]**

Testing Health Checks

[] The testIfServicesAreUp() test case sends a request to the http://localhost:9080/health URL through the 
   connectToHealthEndpoint() method from the HealthTestUtil class
   -> the HealthTestUtil class is inside backticks. I don't think `class` should be there.

**[You are reviewing an older version]**

[] This private method uses the getActualState() method from the HealthTestUtil class to parse the actual 
    state of each services in the JsonArray result." 
    -> Remove the " after 'result.'

**[ fixed]**

**Comment by evelinec** [comment]
I thought I made a comment to fix the first point mentioned here.. is that not fixed?

**Comment by evelinec** [comment]
The 2nd point about URL is fine.

**Comment by Ahmad-Ayyoub** [comment]
OK I deleted that message now.

**Comment by evelinec** [comment]
About the 2nd point, actually we can get rid of the bullet point for the URL.

**Comment by Ahmad-Ayyoub** [comment]
Fixed to: 
While the server is running, navigate to the `http://localhost:9080/health` URL to find the
the states of the two services.

**Comment by Ahmad-Ayyoub** [comment]
https://github.com/OpenLiberty/draft-guide-microprofile-health/pull/36/commits/fc5724c8844f75acf298c674e6925ed01b95bddf

**Comment by evelinec** [comment]
Addressed all issues.
