### ISSUE TITLE
User Review

### ISSUE THREAD

**Issue by gkertaseferi** [OpenLiberty/draft-guide-microprofile-health#5]
1.What you'll learn
Before the service reports its states, it should check what it needs or has. --> what it needs or has? 
    - Maybe there is a better way of saying this.

2.Adding health check to inventory service
    - This service reports its healthy state depending on these two self checks: (I don't really understand 
       what the self checks are).
    - This property is used this file to manipulate on the state of the service. --> used in this file?? .  
    - You are also using this file 3 times, maybe you should be more specific and try to rephrase? 
    - The service reports the system properties for a hostname through calling getPropertiesForHost() 
       method. --> the getPropertiesForHost() method?

3.Testing health check 
    - The static keyword with curly brackets is used to initializes the static fields. --> to initialize???
    - They are the JsonArray that hold the states of the services, the two maps for storing the states when 
       the services are up and when they are down and the constant to hold the property that will be read. 
       --> who are they??
    - The @After annotations is placed --> are placed? or annotation?
    - The testIfServicesAreUp() method sends a request to /health endpoint then verifies the 200 response 
      code is returned. --> to /health endpoint and then it verifies (or just put a comma after /health 
      endpoint).
    - It does that using connectToHealthEndpoint() helper method. Then, this JsonArray is passed to 
      checkServicesStates() method to compare and assert it with the expected services states. It does that 
      using getActualState() helper method which --> two sentences starting with It does that?  and also 
      you are referring to some methods with "the" <methodName> method and to others without "the".

**Comment by Ahmad-Ayyoub** [comment]
Updated here: https://github.com/OpenLiberty/draft-guide-microprofile-health/pull/6
