### ISSUE TITLE
What you'll learn - review comments

### ISSUE THREAD

**Issue by rlcundiff** [OpenLiberty/draft-guide-microprofile-health#7]
"knowing which services are performing in the application."  -> Health checks aren't for knowing which services are in an app.  Maybe this was meant to be "knowing how services are performing in the application."  In any case, I think that whole sentence would be better as "The great benefit from adding a health check is that it allows your service to participate in the decision making process about its health."

Because there can be consequences to a DOWN result, at the end of the third paragraph I suggest adding the following sentence: "It is important to note that a DOWN result can be used by a service orchestrator to drive decisions about when to replace an instance of a service."

**Comment by Ahmad-Ayyoub** [comment]
Fixed here: https://github.com/OpenLiberty/draft-guide-microprofile-health/pull/8 
@rlcundiff Just look at the adoc only. Thanks for your review.
