### ISSUE TITLE
User Review

### ISSUE THREAD

**Issue by gkertaseferi** [OpenLiberty/draft-guide-microprofile-health#9]
1. Adding health check to inventory service
`Now, open inventory service from /start/src/main/java/io/openliberty/guides/inventory/InventoryResource to add a condition to it.`
I don't know if this is something you need to say or you just forgot to delete it from `/start/src/main/java/io/openliberty/guides/inventory/InventoryResource`. Right now it's the same for both start and finish so I can't add what you are saying.
[Ok this needs to be fixed]

2. Testing health check
Where is the `HealthTestUtil.java` in the guide? without adding it the tests don't pass.
[We do not talk about helper class, look at other guides]

3. Also the `Getting Started` section is missing too. [It is not missing, it is replaced by this link:
https://raw.githubusercontent.com/OpenLiberty/guides-common/master/gitclone.adoc]

**Comment by Ahmad-Ayyoub** [comment]
Fixed here: https://github.com/OpenLiberty/draft-guide-microprofile-health/commit/7edb330b1d8ee6ad3dc915773ff3b96cb74e4ce5
